services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run:/host/var/run:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_VAR_RUN=/host/var/run
      - STATIC_DIR=./frontend/dist
    privileged: true # Required for accessing host metrics
    pid: "host" # Required for accessing host process information
    restart: unless-stopped
